apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-data-service
  namespace: healthcare-platform
spec:
  replicas: 3
  selector:
    matchLabels:
      app: patient-data-service
  template:
    metadata:
      labels:
        app: patient-data-service
    spec:
      containers:
      - name: patient-data-service
        image: healthcare-platform/patient-data-service:1.0.0
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        - name: DB_HOST
          value: "postgres-service"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/v1/actuator/health
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/v1/actuator/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: patient-data-service
  namespace: healthcare-platform
spec:
  selector:
    app: patient-data-service
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP